[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["npm install", "npm run build"]

[start]
cmd = "php artisan config:cache && php artisan serve --host=0.0.0.0 --port=$PORT"
